// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestData.proto

package com.tradeshift.reaktive.replication;

public final class TestData {
  private TestData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TestEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.tradeshift.reaktive.replication.TestEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string msg = 1;</code>
     */
    boolean hasMsg();
    /**
     * <code>required string msg = 1;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>required string msg = 1;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code com.tradeshift.reaktive.replication.TestEvent}
   */
  public static final class TestEvent extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.tradeshift.reaktive.replication.TestEvent)
      TestEventOrBuilder {
    // Use TestEvent.newBuilder() to construct.
    private TestEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TestEvent(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TestEvent defaultInstance;
    public static TestEvent getDefaultInstance() {
      return defaultInstance;
    }

    public TestEvent getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TestEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              msg_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tradeshift.reaktive.replication.TestData.internal_static_com_tradeshift_reaktive_replication_TestEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tradeshift.reaktive.replication.TestData.internal_static_com_tradeshift_reaktive_replication_TestEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tradeshift.reaktive.replication.TestData.TestEvent.class, com.tradeshift.reaktive.replication.TestData.TestEvent.Builder.class);
    }

    public static com.google.protobuf.Parser<TestEvent> PARSER =
        new com.google.protobuf.AbstractParser<TestEvent>() {
      public TestEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestEvent(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TestEvent> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MSG_FIELD_NUMBER = 1;
    private java.lang.Object msg_;
    /**
     * <code>required string msg = 1;</code>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string msg = 1;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string msg = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      msg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.tradeshift.reaktive.replication.TestData.TestEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tradeshift.reaktive.replication.TestData.TestEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tradeshift.reaktive.replication.TestData.TestEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tradeshift.reaktive.replication.TestData.TestEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tradeshift.reaktive.replication.TestData.TestEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tradeshift.reaktive.replication.TestData.TestEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.tradeshift.reaktive.replication.TestData.TestEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.tradeshift.reaktive.replication.TestData.TestEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.tradeshift.reaktive.replication.TestData.TestEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tradeshift.reaktive.replication.TestData.TestEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tradeshift.reaktive.replication.TestData.TestEvent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.tradeshift.reaktive.replication.TestEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.tradeshift.reaktive.replication.TestEvent)
        com.tradeshift.reaktive.replication.TestData.TestEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tradeshift.reaktive.replication.TestData.internal_static_com_tradeshift_reaktive_replication_TestEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tradeshift.reaktive.replication.TestData.internal_static_com_tradeshift_reaktive_replication_TestEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tradeshift.reaktive.replication.TestData.TestEvent.class, com.tradeshift.reaktive.replication.TestData.TestEvent.Builder.class);
      }

      // Construct using com.tradeshift.reaktive.replication.TestData.TestEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tradeshift.reaktive.replication.TestData.internal_static_com_tradeshift_reaktive_replication_TestEvent_descriptor;
      }

      public com.tradeshift.reaktive.replication.TestData.TestEvent getDefaultInstanceForType() {
        return com.tradeshift.reaktive.replication.TestData.TestEvent.getDefaultInstance();
      }

      public com.tradeshift.reaktive.replication.TestData.TestEvent build() {
        com.tradeshift.reaktive.replication.TestData.TestEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tradeshift.reaktive.replication.TestData.TestEvent buildPartial() {
        com.tradeshift.reaktive.replication.TestData.TestEvent result = new com.tradeshift.reaktive.replication.TestData.TestEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msg_ = msg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tradeshift.reaktive.replication.TestData.TestEvent) {
          return mergeFrom((com.tradeshift.reaktive.replication.TestData.TestEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tradeshift.reaktive.replication.TestData.TestEvent other) {
        if (other == com.tradeshift.reaktive.replication.TestData.TestEvent.getDefaultInstance()) return this;
        if (other.hasMsg()) {
          bitField0_ |= 0x00000001;
          msg_ = other.msg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMsg()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tradeshift.reaktive.replication.TestData.TestEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tradeshift.reaktive.replication.TestData.TestEvent) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object msg_ = "";
      /**
       * <code>required string msg = 1;</code>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string msg = 1;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string msg = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string msg = 1;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string msg = 1;</code>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>required string msg = 1;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.tradeshift.reaktive.replication.TestEvent)
    }

    static {
      defaultInstance = new TestEvent(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.tradeshift.reaktive.replication.TestEvent)
  }

  public interface TestCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.tradeshift.reaktive.replication.TestCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .com.tradeshift.reaktive.protobuf.UUID aggregateId = 1;</code>
     */
    boolean hasAggregateId();
    /**
     * <code>required .com.tradeshift.reaktive.protobuf.UUID aggregateId = 1;</code>
     */
    com.tradeshift.reaktive.protobuf.Types.UUID getAggregateId();
    /**
     * <code>required .com.tradeshift.reaktive.protobuf.UUID aggregateId = 1;</code>
     */
    com.tradeshift.reaktive.protobuf.Types.UUIDOrBuilder getAggregateIdOrBuilder();

    /**
     * <code>optional .com.tradeshift.reaktive.replication.TestCommand.Write write = 2;</code>
     */
    boolean hasWrite();
    /**
     * <code>optional .com.tradeshift.reaktive.replication.TestCommand.Write write = 2;</code>
     */
    com.tradeshift.reaktive.replication.TestData.TestCommand.Write getWrite();
    /**
     * <code>optional .com.tradeshift.reaktive.replication.TestCommand.Write write = 2;</code>
     */
    com.tradeshift.reaktive.replication.TestData.TestCommand.WriteOrBuilder getWriteOrBuilder();

    /**
     * <code>optional .com.tradeshift.reaktive.replication.TestCommand.Read read = 3;</code>
     */
    boolean hasRead();
    /**
     * <code>optional .com.tradeshift.reaktive.replication.TestCommand.Read read = 3;</code>
     */
    com.tradeshift.reaktive.replication.TestData.TestCommand.Read getRead();
    /**
     * <code>optional .com.tradeshift.reaktive.replication.TestCommand.Read read = 3;</code>
     */
    com.tradeshift.reaktive.replication.TestData.TestCommand.ReadOrBuilder getReadOrBuilder();
  }
  /**
   * Protobuf type {@code com.tradeshift.reaktive.replication.TestCommand}
   */
  public static final class TestCommand extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.tradeshift.reaktive.replication.TestCommand)
      TestCommandOrBuilder {
    // Use TestCommand.newBuilder() to construct.
    private TestCommand(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TestCommand(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TestCommand defaultInstance;
    public static TestCommand getDefaultInstance() {
      return defaultInstance;
    }

    public TestCommand getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TestCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.tradeshift.reaktive.protobuf.Types.UUID.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = aggregateId_.toBuilder();
              }
              aggregateId_ = input.readMessage(com.tradeshift.reaktive.protobuf.Types.UUID.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(aggregateId_);
                aggregateId_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.tradeshift.reaktive.replication.TestData.TestCommand.Write.Builder subBuilder = null;
              if (bodyCase_ == 2) {
                subBuilder = ((com.tradeshift.reaktive.replication.TestData.TestCommand.Write) body_).toBuilder();
              }
              body_ = input.readMessage(com.tradeshift.reaktive.replication.TestData.TestCommand.Write.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.tradeshift.reaktive.replication.TestData.TestCommand.Write) body_);
                body_ = subBuilder.buildPartial();
              }
              bodyCase_ = 2;
              break;
            }
            case 26: {
              com.tradeshift.reaktive.replication.TestData.TestCommand.Read.Builder subBuilder = null;
              if (bodyCase_ == 3) {
                subBuilder = ((com.tradeshift.reaktive.replication.TestData.TestCommand.Read) body_).toBuilder();
              }
              body_ = input.readMessage(com.tradeshift.reaktive.replication.TestData.TestCommand.Read.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.tradeshift.reaktive.replication.TestData.TestCommand.Read) body_);
                body_ = subBuilder.buildPartial();
              }
              bodyCase_ = 3;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tradeshift.reaktive.replication.TestData.internal_static_com_tradeshift_reaktive_replication_TestCommand_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tradeshift.reaktive.replication.TestData.internal_static_com_tradeshift_reaktive_replication_TestCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tradeshift.reaktive.replication.TestData.TestCommand.class, com.tradeshift.reaktive.replication.TestData.TestCommand.Builder.class);
    }

    public static com.google.protobuf.Parser<TestCommand> PARSER =
        new com.google.protobuf.AbstractParser<TestCommand>() {
      public TestCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestCommand(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TestCommand> getParserForType() {
      return PARSER;
    }

    public interface ReadOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.tradeshift.reaktive.replication.TestCommand.Read)
        com.google.protobuf.MessageOrBuilder {
    }
    /**
     * Protobuf type {@code com.tradeshift.reaktive.replication.TestCommand.Read}
     */
    public static final class Read extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:com.tradeshift.reaktive.replication.TestCommand.Read)
        ReadOrBuilder {
      // Use Read.newBuilder() to construct.
      private Read(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Read(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Read defaultInstance;
      public static Read getDefaultInstance() {
        return defaultInstance;
      }

      public Read getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Read(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tradeshift.reaktive.replication.TestData.internal_static_com_tradeshift_reaktive_replication_TestCommand_Read_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tradeshift.reaktive.replication.TestData.internal_static_com_tradeshift_reaktive_replication_TestCommand_Read_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tradeshift.reaktive.replication.TestData.TestCommand.Read.class, com.tradeshift.reaktive.replication.TestData.TestCommand.Read.Builder.class);
      }

      public static com.google.protobuf.Parser<Read> PARSER =
          new com.google.protobuf.AbstractParser<Read>() {
        public Read parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Read(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Read> getParserForType() {
        return PARSER;
      }

      private void initFields() {
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.tradeshift.reaktive.replication.TestData.TestCommand.Read parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.tradeshift.reaktive.replication.TestData.TestCommand.Read parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.tradeshift.reaktive.replication.TestData.TestCommand.Read parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.tradeshift.reaktive.replication.TestData.TestCommand.Read parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.tradeshift.reaktive.replication.TestData.TestCommand.Read parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.tradeshift.reaktive.replication.TestData.TestCommand.Read parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.tradeshift.reaktive.replication.TestData.TestCommand.Read parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.tradeshift.reaktive.replication.TestData.TestCommand.Read parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.tradeshift.reaktive.replication.TestData.TestCommand.Read parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.tradeshift.reaktive.replication.TestData.TestCommand.Read parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.tradeshift.reaktive.replication.TestData.TestCommand.Read prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.tradeshift.reaktive.replication.TestCommand.Read}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.tradeshift.reaktive.replication.TestCommand.Read)
          com.tradeshift.reaktive.replication.TestData.TestCommand.ReadOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.tradeshift.reaktive.replication.TestData.internal_static_com_tradeshift_reaktive_replication_TestCommand_Read_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.tradeshift.reaktive.replication.TestData.internal_static_com_tradeshift_reaktive_replication_TestCommand_Read_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.tradeshift.reaktive.replication.TestData.TestCommand.Read.class, com.tradeshift.reaktive.replication.TestData.TestCommand.Read.Builder.class);
        }

        // Construct using com.tradeshift.reaktive.replication.TestData.TestCommand.Read.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.tradeshift.reaktive.replication.TestData.internal_static_com_tradeshift_reaktive_replication_TestCommand_Read_descriptor;
        }

        public com.tradeshift.reaktive.replication.TestData.TestCommand.Read getDefaultInstanceForType() {
          return com.tradeshift.reaktive.replication.TestData.TestCommand.Read.getDefaultInstance();
        }

        public com.tradeshift.reaktive.replication.TestData.TestCommand.Read build() {
          com.tradeshift.reaktive.replication.TestData.TestCommand.Read result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.tradeshift.reaktive.replication.TestData.TestCommand.Read buildPartial() {
          com.tradeshift.reaktive.replication.TestData.TestCommand.Read result = new com.tradeshift.reaktive.replication.TestData.TestCommand.Read(this);
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.tradeshift.reaktive.replication.TestData.TestCommand.Read) {
            return mergeFrom((com.tradeshift.reaktive.replication.TestData.TestCommand.Read)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.tradeshift.reaktive.replication.TestData.TestCommand.Read other) {
          if (other == com.tradeshift.reaktive.replication.TestData.TestCommand.Read.getDefaultInstance()) return this;
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.tradeshift.reaktive.replication.TestData.TestCommand.Read parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.tradeshift.reaktive.replication.TestData.TestCommand.Read) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.tradeshift.reaktive.replication.TestCommand.Read)
      }

      static {
        defaultInstance = new Read(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.tradeshift.reaktive.replication.TestCommand.Read)
    }

    public interface WriteOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.tradeshift.reaktive.replication.TestCommand.Write)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string msg = 1;</code>
       */
      boolean hasMsg();
      /**
       * <code>required string msg = 1;</code>
       */
      java.lang.String getMsg();
      /**
       * <code>required string msg = 1;</code>
       */
      com.google.protobuf.ByteString
          getMsgBytes();
    }
    /**
     * Protobuf type {@code com.tradeshift.reaktive.replication.TestCommand.Write}
     */
    public static final class Write extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:com.tradeshift.reaktive.replication.TestCommand.Write)
        WriteOrBuilder {
      // Use Write.newBuilder() to construct.
      private Write(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Write(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Write defaultInstance;
      public static Write getDefaultInstance() {
        return defaultInstance;
      }

      public Write getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Write(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                msg_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tradeshift.reaktive.replication.TestData.internal_static_com_tradeshift_reaktive_replication_TestCommand_Write_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tradeshift.reaktive.replication.TestData.internal_static_com_tradeshift_reaktive_replication_TestCommand_Write_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tradeshift.reaktive.replication.TestData.TestCommand.Write.class, com.tradeshift.reaktive.replication.TestData.TestCommand.Write.Builder.class);
      }

      public static com.google.protobuf.Parser<Write> PARSER =
          new com.google.protobuf.AbstractParser<Write>() {
        public Write parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Write(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Write> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int MSG_FIELD_NUMBER = 1;
      private java.lang.Object msg_;
      /**
       * <code>required string msg = 1;</code>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string msg = 1;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msg_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string msg = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        msg_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasMsg()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getMsgBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getMsgBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.tradeshift.reaktive.replication.TestData.TestCommand.Write parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.tradeshift.reaktive.replication.TestData.TestCommand.Write parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.tradeshift.reaktive.replication.TestData.TestCommand.Write parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.tradeshift.reaktive.replication.TestData.TestCommand.Write parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.tradeshift.reaktive.replication.TestData.TestCommand.Write parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.tradeshift.reaktive.replication.TestData.TestCommand.Write parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.tradeshift.reaktive.replication.TestData.TestCommand.Write parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.tradeshift.reaktive.replication.TestData.TestCommand.Write parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.tradeshift.reaktive.replication.TestData.TestCommand.Write parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.tradeshift.reaktive.replication.TestData.TestCommand.Write parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.tradeshift.reaktive.replication.TestData.TestCommand.Write prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.tradeshift.reaktive.replication.TestCommand.Write}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.tradeshift.reaktive.replication.TestCommand.Write)
          com.tradeshift.reaktive.replication.TestData.TestCommand.WriteOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.tradeshift.reaktive.replication.TestData.internal_static_com_tradeshift_reaktive_replication_TestCommand_Write_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.tradeshift.reaktive.replication.TestData.internal_static_com_tradeshift_reaktive_replication_TestCommand_Write_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.tradeshift.reaktive.replication.TestData.TestCommand.Write.class, com.tradeshift.reaktive.replication.TestData.TestCommand.Write.Builder.class);
        }

        // Construct using com.tradeshift.reaktive.replication.TestData.TestCommand.Write.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          msg_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.tradeshift.reaktive.replication.TestData.internal_static_com_tradeshift_reaktive_replication_TestCommand_Write_descriptor;
        }

        public com.tradeshift.reaktive.replication.TestData.TestCommand.Write getDefaultInstanceForType() {
          return com.tradeshift.reaktive.replication.TestData.TestCommand.Write.getDefaultInstance();
        }

        public com.tradeshift.reaktive.replication.TestData.TestCommand.Write build() {
          com.tradeshift.reaktive.replication.TestData.TestCommand.Write result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.tradeshift.reaktive.replication.TestData.TestCommand.Write buildPartial() {
          com.tradeshift.reaktive.replication.TestData.TestCommand.Write result = new com.tradeshift.reaktive.replication.TestData.TestCommand.Write(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.msg_ = msg_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.tradeshift.reaktive.replication.TestData.TestCommand.Write) {
            return mergeFrom((com.tradeshift.reaktive.replication.TestData.TestCommand.Write)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.tradeshift.reaktive.replication.TestData.TestCommand.Write other) {
          if (other == com.tradeshift.reaktive.replication.TestData.TestCommand.Write.getDefaultInstance()) return this;
          if (other.hasMsg()) {
            bitField0_ |= 0x00000001;
            msg_ = other.msg_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasMsg()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.tradeshift.reaktive.replication.TestData.TestCommand.Write parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.tradeshift.reaktive.replication.TestData.TestCommand.Write) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object msg_ = "";
        /**
         * <code>required string msg = 1;</code>
         */
        public boolean hasMsg() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string msg = 1;</code>
         */
        public java.lang.String getMsg() {
          java.lang.Object ref = msg_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              msg_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string msg = 1;</code>
         */
        public com.google.protobuf.ByteString
            getMsgBytes() {
          java.lang.Object ref = msg_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            msg_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string msg = 1;</code>
         */
        public Builder setMsg(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          msg_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string msg = 1;</code>
         */
        public Builder clearMsg() {
          bitField0_ = (bitField0_ & ~0x00000001);
          msg_ = getDefaultInstance().getMsg();
          onChanged();
          return this;
        }
        /**
         * <code>required string msg = 1;</code>
         */
        public Builder setMsgBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          msg_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.tradeshift.reaktive.replication.TestCommand.Write)
      }

      static {
        defaultInstance = new Write(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.tradeshift.reaktive.replication.TestCommand.Write)
    }

    private int bitField0_;
    private int bodyCase_ = 0;
    private java.lang.Object body_;
    public enum BodyCase
        implements com.google.protobuf.Internal.EnumLite {
      WRITE(2),
      READ(3),
      BODY_NOT_SET(0);
      private int value = 0;
      private BodyCase(int value) {
        this.value = value;
      }
      public static BodyCase valueOf(int value) {
        switch (value) {
          case 2: return WRITE;
          case 3: return READ;
          case 0: return BODY_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public BodyCase
    getBodyCase() {
      return BodyCase.valueOf(
          bodyCase_);
    }

    public static final int AGGREGATEID_FIELD_NUMBER = 1;
    private com.tradeshift.reaktive.protobuf.Types.UUID aggregateId_;
    /**
     * <code>required .com.tradeshift.reaktive.protobuf.UUID aggregateId = 1;</code>
     */
    public boolean hasAggregateId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.tradeshift.reaktive.protobuf.UUID aggregateId = 1;</code>
     */
    public com.tradeshift.reaktive.protobuf.Types.UUID getAggregateId() {
      return aggregateId_;
    }
    /**
     * <code>required .com.tradeshift.reaktive.protobuf.UUID aggregateId = 1;</code>
     */
    public com.tradeshift.reaktive.protobuf.Types.UUIDOrBuilder getAggregateIdOrBuilder() {
      return aggregateId_;
    }

    public static final int WRITE_FIELD_NUMBER = 2;
    /**
     * <code>optional .com.tradeshift.reaktive.replication.TestCommand.Write write = 2;</code>
     */
    public boolean hasWrite() {
      return bodyCase_ == 2;
    }
    /**
     * <code>optional .com.tradeshift.reaktive.replication.TestCommand.Write write = 2;</code>
     */
    public com.tradeshift.reaktive.replication.TestData.TestCommand.Write getWrite() {
      if (bodyCase_ == 2) {
         return (com.tradeshift.reaktive.replication.TestData.TestCommand.Write) body_;
      }
      return com.tradeshift.reaktive.replication.TestData.TestCommand.Write.getDefaultInstance();
    }
    /**
     * <code>optional .com.tradeshift.reaktive.replication.TestCommand.Write write = 2;</code>
     */
    public com.tradeshift.reaktive.replication.TestData.TestCommand.WriteOrBuilder getWriteOrBuilder() {
      if (bodyCase_ == 2) {
         return (com.tradeshift.reaktive.replication.TestData.TestCommand.Write) body_;
      }
      return com.tradeshift.reaktive.replication.TestData.TestCommand.Write.getDefaultInstance();
    }

    public static final int READ_FIELD_NUMBER = 3;
    /**
     * <code>optional .com.tradeshift.reaktive.replication.TestCommand.Read read = 3;</code>
     */
    public boolean hasRead() {
      return bodyCase_ == 3;
    }
    /**
     * <code>optional .com.tradeshift.reaktive.replication.TestCommand.Read read = 3;</code>
     */
    public com.tradeshift.reaktive.replication.TestData.TestCommand.Read getRead() {
      if (bodyCase_ == 3) {
         return (com.tradeshift.reaktive.replication.TestData.TestCommand.Read) body_;
      }
      return com.tradeshift.reaktive.replication.TestData.TestCommand.Read.getDefaultInstance();
    }
    /**
     * <code>optional .com.tradeshift.reaktive.replication.TestCommand.Read read = 3;</code>
     */
    public com.tradeshift.reaktive.replication.TestData.TestCommand.ReadOrBuilder getReadOrBuilder() {
      if (bodyCase_ == 3) {
         return (com.tradeshift.reaktive.replication.TestData.TestCommand.Read) body_;
      }
      return com.tradeshift.reaktive.replication.TestData.TestCommand.Read.getDefaultInstance();
    }

    private void initFields() {
      aggregateId_ = com.tradeshift.reaktive.protobuf.Types.UUID.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAggregateId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getAggregateId().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasWrite()) {
        if (!getWrite().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, aggregateId_);
      }
      if (bodyCase_ == 2) {
        output.writeMessage(2, (com.tradeshift.reaktive.replication.TestData.TestCommand.Write) body_);
      }
      if (bodyCase_ == 3) {
        output.writeMessage(3, (com.tradeshift.reaktive.replication.TestData.TestCommand.Read) body_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, aggregateId_);
      }
      if (bodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.tradeshift.reaktive.replication.TestData.TestCommand.Write) body_);
      }
      if (bodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (com.tradeshift.reaktive.replication.TestData.TestCommand.Read) body_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.tradeshift.reaktive.replication.TestData.TestCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tradeshift.reaktive.replication.TestData.TestCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tradeshift.reaktive.replication.TestData.TestCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tradeshift.reaktive.replication.TestData.TestCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tradeshift.reaktive.replication.TestData.TestCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tradeshift.reaktive.replication.TestData.TestCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.tradeshift.reaktive.replication.TestData.TestCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.tradeshift.reaktive.replication.TestData.TestCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.tradeshift.reaktive.replication.TestData.TestCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tradeshift.reaktive.replication.TestData.TestCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tradeshift.reaktive.replication.TestData.TestCommand prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.tradeshift.reaktive.replication.TestCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.tradeshift.reaktive.replication.TestCommand)
        com.tradeshift.reaktive.replication.TestData.TestCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tradeshift.reaktive.replication.TestData.internal_static_com_tradeshift_reaktive_replication_TestCommand_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tradeshift.reaktive.replication.TestData.internal_static_com_tradeshift_reaktive_replication_TestCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tradeshift.reaktive.replication.TestData.TestCommand.class, com.tradeshift.reaktive.replication.TestData.TestCommand.Builder.class);
      }

      // Construct using com.tradeshift.reaktive.replication.TestData.TestCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAggregateIdFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (aggregateIdBuilder_ == null) {
          aggregateId_ = com.tradeshift.reaktive.protobuf.Types.UUID.getDefaultInstance();
        } else {
          aggregateIdBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        bodyCase_ = 0;
        body_ = null;
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tradeshift.reaktive.replication.TestData.internal_static_com_tradeshift_reaktive_replication_TestCommand_descriptor;
      }

      public com.tradeshift.reaktive.replication.TestData.TestCommand getDefaultInstanceForType() {
        return com.tradeshift.reaktive.replication.TestData.TestCommand.getDefaultInstance();
      }

      public com.tradeshift.reaktive.replication.TestData.TestCommand build() {
        com.tradeshift.reaktive.replication.TestData.TestCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tradeshift.reaktive.replication.TestData.TestCommand buildPartial() {
        com.tradeshift.reaktive.replication.TestData.TestCommand result = new com.tradeshift.reaktive.replication.TestData.TestCommand(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (aggregateIdBuilder_ == null) {
          result.aggregateId_ = aggregateId_;
        } else {
          result.aggregateId_ = aggregateIdBuilder_.build();
        }
        if (bodyCase_ == 2) {
          if (writeBuilder_ == null) {
            result.body_ = body_;
          } else {
            result.body_ = writeBuilder_.build();
          }
        }
        if (bodyCase_ == 3) {
          if (readBuilder_ == null) {
            result.body_ = body_;
          } else {
            result.body_ = readBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.bodyCase_ = bodyCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tradeshift.reaktive.replication.TestData.TestCommand) {
          return mergeFrom((com.tradeshift.reaktive.replication.TestData.TestCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tradeshift.reaktive.replication.TestData.TestCommand other) {
        if (other == com.tradeshift.reaktive.replication.TestData.TestCommand.getDefaultInstance()) return this;
        if (other.hasAggregateId()) {
          mergeAggregateId(other.getAggregateId());
        }
        switch (other.getBodyCase()) {
          case WRITE: {
            mergeWrite(other.getWrite());
            break;
          }
          case READ: {
            mergeRead(other.getRead());
            break;
          }
          case BODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAggregateId()) {
          
          return false;
        }
        if (!getAggregateId().isInitialized()) {
          
          return false;
        }
        if (hasWrite()) {
          if (!getWrite().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tradeshift.reaktive.replication.TestData.TestCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tradeshift.reaktive.replication.TestData.TestCommand) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bodyCase_ = 0;
      private java.lang.Object body_;
      public BodyCase
          getBodyCase() {
        return BodyCase.valueOf(
            bodyCase_);
      }

      public Builder clearBody() {
        bodyCase_ = 0;
        body_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.tradeshift.reaktive.protobuf.Types.UUID aggregateId_ = com.tradeshift.reaktive.protobuf.Types.UUID.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.tradeshift.reaktive.protobuf.Types.UUID, com.tradeshift.reaktive.protobuf.Types.UUID.Builder, com.tradeshift.reaktive.protobuf.Types.UUIDOrBuilder> aggregateIdBuilder_;
      /**
       * <code>required .com.tradeshift.reaktive.protobuf.UUID aggregateId = 1;</code>
       */
      public boolean hasAggregateId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.tradeshift.reaktive.protobuf.UUID aggregateId = 1;</code>
       */
      public com.tradeshift.reaktive.protobuf.Types.UUID getAggregateId() {
        if (aggregateIdBuilder_ == null) {
          return aggregateId_;
        } else {
          return aggregateIdBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.tradeshift.reaktive.protobuf.UUID aggregateId = 1;</code>
       */
      public Builder setAggregateId(com.tradeshift.reaktive.protobuf.Types.UUID value) {
        if (aggregateIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          aggregateId_ = value;
          onChanged();
        } else {
          aggregateIdBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.tradeshift.reaktive.protobuf.UUID aggregateId = 1;</code>
       */
      public Builder setAggregateId(
          com.tradeshift.reaktive.protobuf.Types.UUID.Builder builderForValue) {
        if (aggregateIdBuilder_ == null) {
          aggregateId_ = builderForValue.build();
          onChanged();
        } else {
          aggregateIdBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.tradeshift.reaktive.protobuf.UUID aggregateId = 1;</code>
       */
      public Builder mergeAggregateId(com.tradeshift.reaktive.protobuf.Types.UUID value) {
        if (aggregateIdBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              aggregateId_ != com.tradeshift.reaktive.protobuf.Types.UUID.getDefaultInstance()) {
            aggregateId_ =
              com.tradeshift.reaktive.protobuf.Types.UUID.newBuilder(aggregateId_).mergeFrom(value).buildPartial();
          } else {
            aggregateId_ = value;
          }
          onChanged();
        } else {
          aggregateIdBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.tradeshift.reaktive.protobuf.UUID aggregateId = 1;</code>
       */
      public Builder clearAggregateId() {
        if (aggregateIdBuilder_ == null) {
          aggregateId_ = com.tradeshift.reaktive.protobuf.Types.UUID.getDefaultInstance();
          onChanged();
        } else {
          aggregateIdBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .com.tradeshift.reaktive.protobuf.UUID aggregateId = 1;</code>
       */
      public com.tradeshift.reaktive.protobuf.Types.UUID.Builder getAggregateIdBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getAggregateIdFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.tradeshift.reaktive.protobuf.UUID aggregateId = 1;</code>
       */
      public com.tradeshift.reaktive.protobuf.Types.UUIDOrBuilder getAggregateIdOrBuilder() {
        if (aggregateIdBuilder_ != null) {
          return aggregateIdBuilder_.getMessageOrBuilder();
        } else {
          return aggregateId_;
        }
      }
      /**
       * <code>required .com.tradeshift.reaktive.protobuf.UUID aggregateId = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.tradeshift.reaktive.protobuf.Types.UUID, com.tradeshift.reaktive.protobuf.Types.UUID.Builder, com.tradeshift.reaktive.protobuf.Types.UUIDOrBuilder> 
          getAggregateIdFieldBuilder() {
        if (aggregateIdBuilder_ == null) {
          aggregateIdBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.tradeshift.reaktive.protobuf.Types.UUID, com.tradeshift.reaktive.protobuf.Types.UUID.Builder, com.tradeshift.reaktive.protobuf.Types.UUIDOrBuilder>(
                  getAggregateId(),
                  getParentForChildren(),
                  isClean());
          aggregateId_ = null;
        }
        return aggregateIdBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          com.tradeshift.reaktive.replication.TestData.TestCommand.Write, com.tradeshift.reaktive.replication.TestData.TestCommand.Write.Builder, com.tradeshift.reaktive.replication.TestData.TestCommand.WriteOrBuilder> writeBuilder_;
      /**
       * <code>optional .com.tradeshift.reaktive.replication.TestCommand.Write write = 2;</code>
       */
      public boolean hasWrite() {
        return bodyCase_ == 2;
      }
      /**
       * <code>optional .com.tradeshift.reaktive.replication.TestCommand.Write write = 2;</code>
       */
      public com.tradeshift.reaktive.replication.TestData.TestCommand.Write getWrite() {
        if (writeBuilder_ == null) {
          if (bodyCase_ == 2) {
            return (com.tradeshift.reaktive.replication.TestData.TestCommand.Write) body_;
          }
          return com.tradeshift.reaktive.replication.TestData.TestCommand.Write.getDefaultInstance();
        } else {
          if (bodyCase_ == 2) {
            return writeBuilder_.getMessage();
          }
          return com.tradeshift.reaktive.replication.TestData.TestCommand.Write.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.tradeshift.reaktive.replication.TestCommand.Write write = 2;</code>
       */
      public Builder setWrite(com.tradeshift.reaktive.replication.TestData.TestCommand.Write value) {
        if (writeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          writeBuilder_.setMessage(value);
        }
        bodyCase_ = 2;
        return this;
      }
      /**
       * <code>optional .com.tradeshift.reaktive.replication.TestCommand.Write write = 2;</code>
       */
      public Builder setWrite(
          com.tradeshift.reaktive.replication.TestData.TestCommand.Write.Builder builderForValue) {
        if (writeBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          writeBuilder_.setMessage(builderForValue.build());
        }
        bodyCase_ = 2;
        return this;
      }
      /**
       * <code>optional .com.tradeshift.reaktive.replication.TestCommand.Write write = 2;</code>
       */
      public Builder mergeWrite(com.tradeshift.reaktive.replication.TestData.TestCommand.Write value) {
        if (writeBuilder_ == null) {
          if (bodyCase_ == 2 &&
              body_ != com.tradeshift.reaktive.replication.TestData.TestCommand.Write.getDefaultInstance()) {
            body_ = com.tradeshift.reaktive.replication.TestData.TestCommand.Write.newBuilder((com.tradeshift.reaktive.replication.TestData.TestCommand.Write) body_)
                .mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          if (bodyCase_ == 2) {
            writeBuilder_.mergeFrom(value);
          }
          writeBuilder_.setMessage(value);
        }
        bodyCase_ = 2;
        return this;
      }
      /**
       * <code>optional .com.tradeshift.reaktive.replication.TestCommand.Write write = 2;</code>
       */
      public Builder clearWrite() {
        if (writeBuilder_ == null) {
          if (bodyCase_ == 2) {
            bodyCase_ = 0;
            body_ = null;
            onChanged();
          }
        } else {
          if (bodyCase_ == 2) {
            bodyCase_ = 0;
            body_ = null;
          }
          writeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .com.tradeshift.reaktive.replication.TestCommand.Write write = 2;</code>
       */
      public com.tradeshift.reaktive.replication.TestData.TestCommand.Write.Builder getWriteBuilder() {
        return getWriteFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.tradeshift.reaktive.replication.TestCommand.Write write = 2;</code>
       */
      public com.tradeshift.reaktive.replication.TestData.TestCommand.WriteOrBuilder getWriteOrBuilder() {
        if ((bodyCase_ == 2) && (writeBuilder_ != null)) {
          return writeBuilder_.getMessageOrBuilder();
        } else {
          if (bodyCase_ == 2) {
            return (com.tradeshift.reaktive.replication.TestData.TestCommand.Write) body_;
          }
          return com.tradeshift.reaktive.replication.TestData.TestCommand.Write.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.tradeshift.reaktive.replication.TestCommand.Write write = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.tradeshift.reaktive.replication.TestData.TestCommand.Write, com.tradeshift.reaktive.replication.TestData.TestCommand.Write.Builder, com.tradeshift.reaktive.replication.TestData.TestCommand.WriteOrBuilder> 
          getWriteFieldBuilder() {
        if (writeBuilder_ == null) {
          if (!(bodyCase_ == 2)) {
            body_ = com.tradeshift.reaktive.replication.TestData.TestCommand.Write.getDefaultInstance();
          }
          writeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.tradeshift.reaktive.replication.TestData.TestCommand.Write, com.tradeshift.reaktive.replication.TestData.TestCommand.Write.Builder, com.tradeshift.reaktive.replication.TestData.TestCommand.WriteOrBuilder>(
                  (com.tradeshift.reaktive.replication.TestData.TestCommand.Write) body_,
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        bodyCase_ = 2;
        return writeBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          com.tradeshift.reaktive.replication.TestData.TestCommand.Read, com.tradeshift.reaktive.replication.TestData.TestCommand.Read.Builder, com.tradeshift.reaktive.replication.TestData.TestCommand.ReadOrBuilder> readBuilder_;
      /**
       * <code>optional .com.tradeshift.reaktive.replication.TestCommand.Read read = 3;</code>
       */
      public boolean hasRead() {
        return bodyCase_ == 3;
      }
      /**
       * <code>optional .com.tradeshift.reaktive.replication.TestCommand.Read read = 3;</code>
       */
      public com.tradeshift.reaktive.replication.TestData.TestCommand.Read getRead() {
        if (readBuilder_ == null) {
          if (bodyCase_ == 3) {
            return (com.tradeshift.reaktive.replication.TestData.TestCommand.Read) body_;
          }
          return com.tradeshift.reaktive.replication.TestData.TestCommand.Read.getDefaultInstance();
        } else {
          if (bodyCase_ == 3) {
            return readBuilder_.getMessage();
          }
          return com.tradeshift.reaktive.replication.TestData.TestCommand.Read.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.tradeshift.reaktive.replication.TestCommand.Read read = 3;</code>
       */
      public Builder setRead(com.tradeshift.reaktive.replication.TestData.TestCommand.Read value) {
        if (readBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          readBuilder_.setMessage(value);
        }
        bodyCase_ = 3;
        return this;
      }
      /**
       * <code>optional .com.tradeshift.reaktive.replication.TestCommand.Read read = 3;</code>
       */
      public Builder setRead(
          com.tradeshift.reaktive.replication.TestData.TestCommand.Read.Builder builderForValue) {
        if (readBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          readBuilder_.setMessage(builderForValue.build());
        }
        bodyCase_ = 3;
        return this;
      }
      /**
       * <code>optional .com.tradeshift.reaktive.replication.TestCommand.Read read = 3;</code>
       */
      public Builder mergeRead(com.tradeshift.reaktive.replication.TestData.TestCommand.Read value) {
        if (readBuilder_ == null) {
          if (bodyCase_ == 3 &&
              body_ != com.tradeshift.reaktive.replication.TestData.TestCommand.Read.getDefaultInstance()) {
            body_ = com.tradeshift.reaktive.replication.TestData.TestCommand.Read.newBuilder((com.tradeshift.reaktive.replication.TestData.TestCommand.Read) body_)
                .mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          if (bodyCase_ == 3) {
            readBuilder_.mergeFrom(value);
          }
          readBuilder_.setMessage(value);
        }
        bodyCase_ = 3;
        return this;
      }
      /**
       * <code>optional .com.tradeshift.reaktive.replication.TestCommand.Read read = 3;</code>
       */
      public Builder clearRead() {
        if (readBuilder_ == null) {
          if (bodyCase_ == 3) {
            bodyCase_ = 0;
            body_ = null;
            onChanged();
          }
        } else {
          if (bodyCase_ == 3) {
            bodyCase_ = 0;
            body_ = null;
          }
          readBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .com.tradeshift.reaktive.replication.TestCommand.Read read = 3;</code>
       */
      public com.tradeshift.reaktive.replication.TestData.TestCommand.Read.Builder getReadBuilder() {
        return getReadFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.tradeshift.reaktive.replication.TestCommand.Read read = 3;</code>
       */
      public com.tradeshift.reaktive.replication.TestData.TestCommand.ReadOrBuilder getReadOrBuilder() {
        if ((bodyCase_ == 3) && (readBuilder_ != null)) {
          return readBuilder_.getMessageOrBuilder();
        } else {
          if (bodyCase_ == 3) {
            return (com.tradeshift.reaktive.replication.TestData.TestCommand.Read) body_;
          }
          return com.tradeshift.reaktive.replication.TestData.TestCommand.Read.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.tradeshift.reaktive.replication.TestCommand.Read read = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.tradeshift.reaktive.replication.TestData.TestCommand.Read, com.tradeshift.reaktive.replication.TestData.TestCommand.Read.Builder, com.tradeshift.reaktive.replication.TestData.TestCommand.ReadOrBuilder> 
          getReadFieldBuilder() {
        if (readBuilder_ == null) {
          if (!(bodyCase_ == 3)) {
            body_ = com.tradeshift.reaktive.replication.TestData.TestCommand.Read.getDefaultInstance();
          }
          readBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.tradeshift.reaktive.replication.TestData.TestCommand.Read, com.tradeshift.reaktive.replication.TestData.TestCommand.Read.Builder, com.tradeshift.reaktive.replication.TestData.TestCommand.ReadOrBuilder>(
                  (com.tradeshift.reaktive.replication.TestData.TestCommand.Read) body_,
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        bodyCase_ = 3;
        return readBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.tradeshift.reaktive.replication.TestCommand)
    }

    static {
      defaultInstance = new TestCommand(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.tradeshift.reaktive.replication.TestCommand)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tradeshift_reaktive_replication_TestEvent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_tradeshift_reaktive_replication_TestEvent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tradeshift_reaktive_replication_TestCommand_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_tradeshift_reaktive_replication_TestCommand_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tradeshift_reaktive_replication_TestCommand_Read_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_tradeshift_reaktive_replication_TestCommand_Read_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tradeshift_reaktive_replication_TestCommand_Write_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_tradeshift_reaktive_replication_TestCommand_Write_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016TestData.proto\022#com.tradeshift.reaktiv" +
      "e.replication\032\013Types.proto\"\030\n\tTestEvent\022" +
      "\013\n\003msg\030\001 \002(\t\"\200\002\n\013TestCommand\022;\n\013aggregat" +
      "eId\030\001 \002(\0132&.com.tradeshift.reaktive.prot" +
      "obuf.UUID\022G\n\005write\030\002 \001(\01326.com.tradeshif" +
      "t.reaktive.replication.TestCommand.Write" +
      "H\000\022E\n\004read\030\003 \001(\01325.com.tradeshift.reakti" +
      "ve.replication.TestCommand.ReadH\000\032\006\n\004Rea" +
      "d\032\024\n\005Write\022\013\n\003msg\030\001 \002(\tB\006\n\004body"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.tradeshift.reaktive.protobuf.Types.getDescriptor(),
        }, assigner);
    internal_static_com_tradeshift_reaktive_replication_TestEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_tradeshift_reaktive_replication_TestEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_tradeshift_reaktive_replication_TestEvent_descriptor,
        new java.lang.String[] { "Msg", });
    internal_static_com_tradeshift_reaktive_replication_TestCommand_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_tradeshift_reaktive_replication_TestCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_tradeshift_reaktive_replication_TestCommand_descriptor,
        new java.lang.String[] { "AggregateId", "Write", "Read", "Body", });
    internal_static_com_tradeshift_reaktive_replication_TestCommand_Read_descriptor =
      internal_static_com_tradeshift_reaktive_replication_TestCommand_descriptor.getNestedTypes().get(0);
    internal_static_com_tradeshift_reaktive_replication_TestCommand_Read_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_tradeshift_reaktive_replication_TestCommand_Read_descriptor,
        new java.lang.String[] { });
    internal_static_com_tradeshift_reaktive_replication_TestCommand_Write_descriptor =
      internal_static_com_tradeshift_reaktive_replication_TestCommand_descriptor.getNestedTypes().get(1);
    internal_static_com_tradeshift_reaktive_replication_TestCommand_Write_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_tradeshift_reaktive_replication_TestCommand_Write_descriptor,
        new java.lang.String[] { "Msg", });
    com.tradeshift.reaktive.protobuf.Types.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
